spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:cristianogomes/PhotoAppConfiguration.git
          clone-on-stat: true
        native:
          search-locations: file:///${user.home}/projects/SpringCloud/PhotoAppConfigFiles