spring:
  application:
    name: PhotoAppApiConfigServer
  cloud:
    config:
      server:
        git:
          uri: git@github.com:cristianogomes/PhotoAppConfiguration.git
          clone-on-stat: true

server:
  port: 8012