server:
  port: 8012

spring:
  application:
    name: PhotoAppApiConfigServer
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/projects/SpringCloud/PhotoAppConfigFiles
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

logging:
  file: log/PhotoAppApiConfigServer.log