server:
  port: 8011

spring:
  application:
    name: zuul
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

api:
  url:
    path:
      registration: /users-ws/users
      login: /users-ws/users/login
      h2console: /users-ws/h2-console/**
      actuator:
        zuul: /actuator/*
        users: /users-ws/actuator/**

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

token:
  secret: 53cr37