server:
  port: ${PORT:0}

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username: photo_app_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: mappings

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gateway:
    ip: 192.168.15.11

token:
  expiration_time: 864000000 #10 days
  secret: 53cr37

login:
  url:
    path: /users/login

feign:
  hystrix:
    enabled: true

logging:
  level:
    com:
      appsdeveloperblog:
        photoapp:
          api:
            users:
              data:
                AlbumsServiceClient: DEBUG