server:
  port: 8010

spring:
  application:
    name: discoveryservice
  security:
    user:
      name: test
      password: test

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

logging:
  file: log/discoveryservice.log